# Generated by Django 3.2.8 on 2021-10-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('price', models.TextField()),
                ('payment_method', models.TextField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
